channels:
- conda-forge
- psi4
- defaults
dependencies:
- black
- cookiecutter
- flake8
- invoke
- jupyterlab
- matplotlib
- numpy
- pandas
- pip
- psi4
- pycodestyle
- pyflakes
- pylint
- python=3.6
- scipy
- sh
