channels:
- conda-forge
- psi4
- defaults
dependencies:
- black
- cookiecutter
- flake8
- invoke
- jupyterlab
- matplotlib
- numpy==1.16.0
- pandas
- pip
- psi4
- psi4-rt
- pycodestyle
- pyflakes
- pylint
- python=3.6
- scipy
- sh
